name: slack-notification

on:
  push:
    branches:
      - master

env:
  SLACK_TOKEN: ${{ secrets.MICHEL_TEST_SLACK_TOKEN }}
  

jobs:
  pull_inot_aws_fe:
  
    name: Slack Notification
    runs-on: ubuntu-20.04

    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: c2-13-51-121-113.eu-north-1.compute.amazonaws.com
        username: ec2-user
        port: 22
        run: |
          echo PULL
          cd repo
          git pull https://github.com/Misk77/quickStart-GithubActions-test-2.git
          

          
    - name: checkout repo
      uses: actions/checkout@v2
      with:
        repository: 'Misk77/quickStart-GithubActions-test-2'
        path: 'GithubActions-test-2'

    - name: List files in the repository
      run: |
        echo "ls github.workspace"
        ls -lah ${{ github.workspace }}
        echo "ls path: 'GithubActions-test-2"
        ls -lah GithubActions-test-2 
    
    - name: Slack Notification Failure
      uses: rtCamp/action-slack-notify@v2
      if: ${{ failure() }}
      env:
        SLACK_MESSAGE: "FAILURE...."
        SLACK_CHANNEL: C038JK97W1G
        SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_TITLE: FIX ME slack-notification-fail
        SLACK_WEBHOOK: ${{ secrets.MICHEL_TEST_SLACK_TOKEN }}
        SLACK_WEBHOOK_TYPE: Michels-solace-order

    - name: Slack Notification Sucess
      uses: rtCamp/action-slack-notify@v2
      if: ${{ success() }}
      env:
        SLACK_MESSAGE: "SUCCESS"
        SLACK_CHANNEL: C038JK97W1G
        SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_TITLE: Updating repo slack-notification-success-1839
        SLACK_WEBHOOK: ${{ secrets.MICHEL_TEST_SLACK_TOKEN }}
        SLACK_WEBHOOK_TYPE: Michels-solace-order
